spring.datasource.url=jdbc:mysql://localhost:3306/realestate_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=yourSuperSecretKeyThatIsAtLeast32CharactersLong
jwt.expiration=86400000